### ISSUE TITLE
Error: post is not defined

### ISSUE THREAD

**Issue by mehrad77** [msudgh/hexo-breadcrumb#1]
Hello and thankyou about this repo

1. I installed package by npm.
2. Added below options to the `config.yml`.
```
breadcrumb:
      display: true
```
3. Then I added `<%- post.breadcrumb.html %>` to my post.ejs (My theme is [cactus](https://github.com/probberechts/hexo-theme-cactus))
4. but when I run `hexo server`, I recived this: 
```ReferenceError: /home/mehrad/Documents/mehrad77.github.io/en/themes/cactus/layout/post.ejs:4
  2|     <header>
  3|     <%- partial('_partial/post/title', { post: page, index: false, class_name: 'posttitle' }) %>
  4|     <%- post.breadcrumb.html %>
  5|     <div class="meta"
post is not defined
```

Can you help me?

**Comment by masoudgs** [comment]
Try this `<%- page.breadcrumb.html %>`.

**Comment by mehrad77** [comment]
Thanks, It worked!
But what's the problem? Why should we use `page` variable instead of `post`?

**Comment by masoudgs** [comment]
I used a partial file in my personal blog theme to call the breadcrumb, like this
```ejs
<%- partial('_partial/post/title', { post: page, index: false, class_name: 'posttitle' }) %>
<%- partial('_partial/post/breadcrumb', { post: page }) %>
```
and then in the breadcrumb file used the `<%- post.breadcrumb.html %>` line.

**Comment by toropanov** [comment]
When I leave only
`<%- page.breadcrumb %>`

without .html in the end. It shows breadcrumb (with no styles) but when I add .html it's disappearing. Strange.

**Comment by masoudgs** [comment]
@toropanov It's a new breaking change, and the package no longer supports the _html_ property. Simplified.
