### ISSUE TITLE
Show category index

### ISSUE THREAD

**Issue by kohki-shikata** [msudgh/hexo-breadcrumb#2]
I use categories at my hexo site and need to show category label and link in breadcrumbs.

Any Idea?

**Comment by masoudgs** [comment]
It's possible, I'm workin on it.

**Comment by kohki-shikata** [comment]
That's great! I'm waiting for it.

**Comment by masoudgs** [comment]
@kohki-shikata Category feature added to breadcrumb. Please have a look if you find it useful.
